<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
    <RootNamespace>ResearchFeatureEngine</RootNamespace>
    <AssemblyName>ResearchFeatureEngine</AssemblyName>
    <ImplicitUsings>disable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <GenerateAssemblyInfo>true</GenerateAssemblyInfo>
    <GenerateAssemblyInformationalVersionAttribute>true</GenerateAssemblyInformationalVersionAttribute>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="cAlgo.API" Version="1.0.0" />
  </ItemGroup>

  <ItemGroup>
    <AssemblyAttribute Include="System.Runtime.CompilerServices.InternalsVisibleTo">
      <_Parameter1>ResearchFeatureEngine.Tests</_Parameter1>
    </AssemblyAttribute>
  </ItemGroup>

  <ItemGroup>
    <Compile Remove="Tests\**" />
    <EmbeddedResource Remove="Tests\**" />
    <None Remove="Tests\**" />
    <Compile Remove="ATRsmooth2\**" />
    <EmbeddedResource Remove="ATRsmooth2\**" />
    <None Remove="ATRsmooth2\**" />
    <Compile Remove="Indicators\**" />
    <EmbeddedResource Remove="Indicators\**" />
    <None Remove="Indicators\**" />
    <Compile Remove="bin\**" />
    <EmbeddedResource Remove="bin\**" />
    <None Remove="bin\**" />
  </ItemGroup>

</Project>
